### ISSUE TITLE
Necromancer Server Crash

### ISSUE THREAD

**Issue by WenXin20** [DavidQF555/ManicWorld#1]
`Minecraft v1.16.5`
`Forge 36.0.1`
`Manic World v1.0.1.1`

After using `/summon` to spawn the necromancer, then went into survival and the necromancer tried to summon a zombie when the server crashed. Spawn eggs would also be nice to see added.
[Crash Report](https://gist.github.com/WenXin20/b93f3328efed5bf75527b9aed271f710)

**Comment by DavidQF555** [comment]
I fixed it. Thank you for reporting this because the bug occurring because I missed something, but just that I accidently wrote the wrong entity. I should be able to make spawn eggs soon.

**Comment by WenXin20** [comment]
Thanks!
